# Generated by Django 5.1.1 on 2024-11-13 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.category'),
        ),
    ]
